development:
  sessions:
    default:
      database: bwphoto_development
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: bwphoto_production
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: bwphoto_test
      hosts:
        - localhost:27017